GET  http://localhost:9000/user

###
// Getuserbyid
GET http://localhost:9000/user/5086058f-f708-4f52-97d4-6ba5cb33160d

###
# createuser
POST http://localhost:9000/user
Content-Type: application/json

{
    "username": "Admin",
    "email": "admin@gmail.com",
    "password": "123",
    "confPassword": "123",
    "role": "admin"
}

###
DELETE http://localhost:9000/user/5086058f-f708-4f52-97d4-6ba5cb33160d


###
# LOGIN USER
POST http://localhost:9000/login
Content-Type: application/json

{
    "email": "ahmad@gmail.com",
    "password": "123"
}

###
GET  http://localhost:9000/me



###
# REGISTER
POST http://localhost:9000/register
Content-Type: application/json

{
    "username": "ahmad",
    "email": "ahmad@gmail.com",
    "password": "1234",
    "confPassword": "1234",

}


###
GET http://localhost:9000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6ImFobWFkIiwiZW1haWwiOiJhaG1hZEBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjc1MjY5MjMyLCJleHAiOjE2NzUyNjkyNTJ9.7iNn3W33MXI0cOBYj0BoYlYjbPbYGs6StcUA11qF8ec


###
DELETE  http://localhost:9000/logout



###
# KERETA
GET http://localhost:9000/class
###
GET http://localhost:9000/train

###
GET http://localhost:9000/train/1

###
POST http://localhost:9000/train
Content-Type: application/json

{
    "id_class": 1,
    "code": "KA342",
    "name": "Sembrani",
    "carriage": "8",
    "seat": "80"
}



###
#Station
GET http://localhost:9000/station

###
GET http://localhost:9000/station/3

###
POST  http://localhost:9000/station
Content-Type: application/json

{
    "name": "PASARSENEN",
    "code": "PSE",
    "city": "JAKARTA"
}

###
PATCH   http://localhost:9000/station/1
Content-Type: application/json

{
    "name": "JATINEGARA",
    "code": "JNG",
    "city": "JAKARTA"
}

###
DELETE  http://localhost:9000/station/3